# Generated by Django 3.0 on 2021-03-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='descount_value',
            new_name='off_value',
        ),
        migrations.RenameField(
            model_name='historicalmeasureunit',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='historicalmeasureunit',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='historicalproductcategory',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='historicalproductcategory',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='descount_value',
            new_name='off_value',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='delete_date',
            new_name='deleted_date',
        ),
    ]
