# Generated by Django 3.0 on 2021-03-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210322_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductcategory',
            name='mesure_unit',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='mesure_unit',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='mesure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.MeasureUnit', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.ProductCategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='mesure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.MeasureUnit', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='product_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.ProductCategory', verbose_name='Categoría de Producto'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='Categoría de Producto'),
        ),
    ]
